[package]
name = "daybar"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = "0.2.2"
chrono = "0.4"
futures = "0.3"
block2 = "0.6"
anyhow = "1"

objc2 = "0.6"

[dependencies.objc2-core-graphics]
version = "0.3"
features = ["CGColor", "CGColorSpace", "CGContext", "CGPath"]

[dependencies.objc2-foundation]
version = "0.3"
features = [
    "NSString",
    "NSGeometry",
    "NSDate",
    "NSArray",
    "NSEnumerator",
    "NSObjCRuntime",
    "NSValue",
    "NSError",
    "NSURL",
    "NSNotification",
    "NSRunLoop",
    "NSThread",
    "NSAttributedString",
    "NSDictionary",
]

[dependencies.objc2-app-kit]
version = "0.3"
features = [
    "NSApplication",
    "NSResponder",
    "NSWindow",
    "NSView",
    "NSControl",
    "NSButton",
    "NSStatusBar",
    "NSStatusItem",
    "NSStatusBarButton",
    "NSImage",
    "NSScreen",
    "NSEvent",
    "NSPanel",
    "NSRunningApplication",
    "NSGraphicsContext",
    "NSAttributedString",
    "NSStringDrawing",
    "NSColor",
    "NSCell",
    "NSFont",
    "block2",
    "objc2-core-foundation",
    "objc2-core-graphics",
]

[dependencies.objc2-event-kit]
version = "0.3"
features = [
    "EKEventStore",
    "EKEvent",
    "EKCalendar",
    "EKCalendarItem",
    "EKParticipant",
    "EKObject",
    "EKTypes",
    "objc2-core-graphics",
    "block2",
]

[profile.release]
opt-level = 2

[lib]
name = "daybar"
path = "src/lib.rs"

[[bin]]
name = "daybar"
path = "src/main.rs"
